extends Node
## Autoload：全局中文。用 Loc.t("key")。

var _strings: Dictionary = {
	"hint.combat_arena": "WASD 移动 | 鼠标瞄准 | 左键普攻 | 右键/QERFC 技能（需装配）\n空格交互 | Tab 背包 | V 属性 | K 技能树\n阶段 A — 俯视火炬式手感",
	"hint.combat_arena_side": "（归档）横版试刀场已不走主路径",
	"hint.pit_floor": "WASD 移动 | 左键普攻 | 右键/QERFC 技能（需装配） | 空格交互\n滚轮切换掉落 | Tab 背包 | V 属性 | K 技能树（回城感悟）",
	"hint.hub": "WASD 移动 | 空格交互设施 | Tab 背包 | V 属性 | K 技能树\n鹤城枢纽 — 委托 / 静室 / 感悟台 / 试刀桩 / 旅店 / 兑换 / 基建 / 觉醒 / 入坑",
	"hint.training_dummy": "WASD 移动 | 左键普攻 | 右键/QERFC 技能 | K 技能树调等级（与感悟台相同，不写盘）\n烙印：战痕/鹰眼/元素/亲和；元素可切火/冰/酸/暗/光，亲和可切动物/植物 | 空格返回鹤城 | 试刀场念力不消耗",
	"hud.interact_pickup_named": "[空格] 拾取 %s",
	"hud.interact_multi": "%s  · 滚轮切换（%d/%d）",
	"hud.bag_btn": "背包",
	"hud.bag_title": "探索背包",
	"hud.bag_close": "关闭（Tab）",
	"hud.skills": "已学技能",
	"hud.skills_learned": "已学 %d 枚符文",
	"hud.mind_value_cap": "念力值 %d/%d",
	"stat.hp": "生命值",
	"stat.mind_value": "念力值",
	"stat.mind_level": "念力等级",
	"stat.vitality": "体力",
	"stat.strength": "力量",
	"stat.patk": "物攻",
	"stat.matk": "魔攻",
	"stat.pdef": "物防",
	"stat.agi": "敏捷",
	"stat.int": "智力",
	"stat.spirit": "精神",
	"stat.luck": "幸运",
	"stat.unspent": "未分配点数",
	"stat.imprint_blade": "战痕·刀",
	"stat.imprint_hot": "鹰眼·弓",
	"stat.imprint_mage": "元素",
	"stat.imprint_affinity": "亲和烙印",
	"training.imprint_cold": "战痕",
	"training.imprint_hot": "鹰眼",
	"training.imprint_mage": "元素",
	"training.imprint_affinity": "亲和",
	"training.imprint_switch": "烙印",
	"training.imprint_switched": "试刀场烙印 → %s（离场还原）",
	"training.element_switch": "元素",
	"training.element_fire": "火",
	"training.element_ice": "冰",
	"training.element_acid": "酸",
	"training.element_dark": "暗",
	"training.element_light": "光",
	"training.element_switched": "试刀场元素 → %s（离场还原）",
	"stat.mage_element": "元素·%s",
	"stat.affinity_kind": "亲和·%s",
	"stat.affinity_kind.animal": "动物",
	"stat.affinity_kind.plant": "植物",
	"training.affinity_switch": "亲和",
	"training.affinity_animal": "动物",
	"training.affinity_plant": "植物",
	"training.affinity_switched": "试刀场亲和 → %s（离场还原）",
	"menu.pick_affinity": "亲和分支",
	"stat.mage_element.fire": "火",
	"stat.mage_element.ice": "冰",
	"stat.mage_element.acid": "酸",
	"stat.mage_element.dark": "暗",
	"stat.mage_element.light": "光",
	"stat.crit": "暴击",
	"stat.critdmg": "爆伤",
	"stat.weapon": "武器",
	"stat.weapon_brand": "烙印·%s",
	"stat.panel_title": "属性",
	"bag.overweight": "承重不足，无法拾取",
	"bag.weight": "承重 %.1f / %.1f",
	"bag.weight_hub": "枢纽不计算承重；入坑后拾取物在此",
	"bag.hub_empty_hint": "材料在材料仓库",
	"bag.expand_ok": "背包扩容至 %d 格",
	"bag.expand_fail": "无法使用",
	"bag.mind_potion_ok": "念力值恢复至 %d/%d",
	"item.paper_note": "金币券",
	"item.paper_note.desc": "轻便的金币等价凭证。购买时按 99 金自动折算，也可兑回金币。",
	"item.bag_expand": "空间扩容符",
	"item.bag_expand.desc": "使用后背包格数 +2。",
	"item.mind_potion": "念力药剂",
	"item.mind_potion.desc": "立即恢复若干念力值（商店购入）。",
	"item.erosion_salve": "清蚀药",
	"item.erosion_salve.desc": "使用后立即降低侵蚀度。入坑前在旅店购买，进坑后从背包使用。",
	"item.erosion_ward": "抗蚀香囊",
	"item.erosion_ward.desc": "使用后本局侵蚀上升速度再减半。入坑前在旅店购买。",
	"bag.erosion_salve_ok": "侵蚀度下降",
	"bag.erosion_ward_ok": "抗蚀香囊生效，侵蚀上升减缓",
	"bag.erosion_ward_already": "抗蚀香囊已在生效",
	"skill.select_hint": "回城感悟台消耗晶核学习职业技能。点图标查看，拖到快捷栏装配。",
	"skill.panel_title": "战痕·刀 · 技能学习",
	"skill.panel_title_hot": "鹰眼·弓 · 技能学习",
	"skill.panel_title_mage": "元素 · 技能学习",
	"skill.panel_title_mage_fire": "元素·火 · 技能学习",
	"skill.panel_title_mage_ice": "元素·冰 · 技能学习",
	"skill.panel_title_mage_acid": "元素·酸 · 技能学习",
	"skill.panel_title_mage_dark": "元素·暗 · 技能学习",
	"skill.panel_title_mage_light": "元素·光 · 技能学习",
	"skill.panel_title_affinity": "亲和烙印 · 技能学习",
	"skill.tab.skill": "技能树",
	"skill.tab.attr": "属性晶核",
	"skill.detail": "%s\n%s\n门槛：探索等级 %d · 晶核%s\n当前探索等级：%d",
	"skill.detail_tree": "%s  %d/%d\n%s\n念力 %s  ·  CD %s\n前置：%s\n%s",
	"skill.kind.active": "主动",
	"skill.kind.passive": "被动",
	"skill.col.slash": "斩",
	"skill.col.break": "破",
	"skill.col.force": "势",
	"skill.col.shot": "射",
	"skill.col.blast": "爆",
	"skill.col.mech": "机",
	"skill.col.spell": "咒",
	"skill.col.zone": "域",
	"skill.col.source": "源",
	"skill.col.frost": "霜",
	"skill.col.rime": "霰",
	"skill.col.flow": "流",
	"skill.col.venom": "蚀",
	"skill.col.mist": "雾",
	"skill.col.flux": "流",
	"skill.col.shade": "影",
	"skill.col.void": "虚",
	"skill.col.veil": "幕",
	"skill.col.radiance": "辉",
	"skill.col.aegis": "盾",
	"skill.col.grace": "恩",
	"skill.col.grove": "林",
	"skill.col.vine": "藤",
	"skill.col.bloom": "绽",
	"skill.col.extra_3": "余",
	"skill.col.extra_4": "衍",
	"hw.caliber": "准星",
	"hw.caliber.effect": "强化弓矢普攻伤害与箭速",
	"hw.sidestep": "闪射",
	"hw.sidestep.effect": "侧步冲刺并放箭",
	"hw.piercer": "贯矢",
	"hw.piercer.effect": "直线高穿箭矢",
	"hw.grenade": "爆裂矛",
	"hw.grenade.effect": "抛物落点爆炸（高噪音）",
	"hw.reload": "连弦",
	"hw.reload.effect": "提高攻速并缩短技能冷却",
	"hw.burst": "连射",
	"hw.burst.effect": "连续短箭齐射",
	"hw.mine": "地刺矛",
	"hw.mine.effect": "脚底延时穿刺（高噪音）",
	"hw.brace": "稳姿",
	"hw.brace.effect": "减伤，技能伤害略增",
	"hw.rail": "贯矛",
	"hw.rail.effect": "蓄力穿透投矛",
	"hw.artillery": "落星矢",
	"hw.artillery.effect": "大范围落点轰击（高噪音）",
	"hw.overclock": "箭雨",
	"hw.overclock.effect": "扇形多箭齐射（高噪音）",
	"mgf.ember": "余烬",
	"mgf.ember.effect": "普攻附带灼烧",
	"mgf.blink": "焰步",
	"mgf.blink.effect": "瞬移并在落点留下燃烧区域",
	"mgf.bolt": "炎弹",
	"mgf.bolt.effect": "射出穿透火球并点燃目标",
	"mgf.nova": "焰爆",
	"mgf.nova.effect": "自身环爆并点燃周围敌人",
	"mgf.focus": "聚灵",
	"mgf.focus.effect": "降低技能念力消耗并加快回念",
	"mgf.lash": "炎束",
	"mgf.lash.effect": "向前发射持续火焰光束",
	"mgf.ring": "火环",
	"mgf.ring.effect": "三颗火球绕身旋转灼烧近敌",
	"mgf.ward": "焰盾",
	"mgf.ward.effect": "减伤，受击反灼烧",
	"mgf.cascade": "炎瀑",
	"mgf.cascade.effect": "抛物线火球雨，落点留火池",
	"mgf.meteor": "陨焰",
	"mgf.meteor.effect": "延迟落点陨石（高噪音）",
	"mgf.cataclysm": "劫火",
	"mgf.cataclysm.effect": "鼠标落点持续燃烧场（高噪音）",
	"mgi.frostmark": "霜痕",
	"mgi.frostmark.effect": "三发冰棱普攻，叠加减速",
	"mgi.froststep": "霜步",
	"mgi.froststep.effect": "瞬移并留下霜迹减速区",
	"mgi.shard": "冰棱",
	"mgi.shard.effect": "射出冰晶叠加寒冻",
	"mgi.rime": "霜环",
	"mgi.rime.effect": "自身结霜环，大幅减速",
	"mgi.permafrost": "凝霜",
	"mgi.permafrost.effect": "延长寒冻并降低冻结阈值",
	"mgi.wall": "冰墙",
	"mgi.wall.effect": "鼠标方向生成冰墙并寒冻贴墙敌人",
	"mgi.pulse": "极寒",
	"mgi.pulse.effect": "脉冲碎裂已冻结目标",
	"mgi.frostarmor": "霜甲",
	"mgi.frostarmor.effect": "攻击寒冻敌人时获得护盾",
	"mgi.rain": "冰雨",
	"mgi.rain.effect": "区域冰棱落地叠加寒冻",
	"mgi.field": "极渊",
	"mgi.field.effect": "极寒持续场，强减速并叠层",
	"mgi.shatter": "碎星",
	"mgi.shatter.effect": "对冻结目标爆发碎裂伤害",
	"mga.stain": "蚀染",
	"mga.stain.effect": "抛物线酸滴普攻，落地留酸池",
	"mga.acidflash": "酸闪",
	"mga.acidflash.effect": "瞬移并在落点留下酸液池",
	"mga.spit": "酸弹",
	"mga.spit.effect": "射出酸弹破甲",
	"mga.cloud": "酸雾",
	"mga.cloud.effect": "扇形持续腐蚀毒雾",
	"mga.dissolve": "溶甲",
	"mga.dissolve.effect": "强化腐蚀破甲效果",
	"mga.etch": "酸蚀",
	"mga.etch.effect": "定向酸液射线持续腐蚀",
	"mga.corrodering": "腐蚀环",
	"mga.corrodering.effect": "酸球绕身旋转腐蚀近敌",
	"mga.resist": "抗酸",
	"mga.resist.effect": "对腐蚀目标额外伤害",
	"mga.rain": "酸雨",
	"mga.rain.effect": "区域酸滴腐蚀",
	"mga.field": "溶地",
	"mga.field.effect": "大范围持续酸池",
	"mga.shatter": "蚀骨",
	"mga.shatter.effect": "对高腐蚀目标爆发伤害",
	"mgd.shadowbite": "影蚀",
	"mgd.shadowbite.effect": "穿透暗影弹普攻，削弱输出",
	"mgd.shadowstep": "影步",
	"mgd.shadowstep.effect": "瞬移并留下暗影削弱区",
	"mgd.bolt": "影弹",
	"mgd.bolt.effect": "穿透暗影弹减攻",
	"mgd.vortex": "影涡",
	"mgd.vortex.effect": "鼠标落点吸聚漩涡并减攻",
	"mgd.darken": "暗蚀",
	"mgd.darken.effect": "强化削弱幅度",
	"mgd.chain": "影链",
	"mgd.chain.effect": "弹射暗影弹，每次减攻",
	"mgd.orbit": "暗环",
	"mgd.orbit.effect": "暗影球绕身，碰敌削弱并吸血",
	"mgd.shadow": "暗影",
	"mgd.shadow.effect": "低血量移速提升并吸血",
	"mgd.rain": "影雨",
	"mgd.rain.effect": "区域暗影弹削弱",
	"mgd.field": "深渊",
	"mgd.field.effect": "大范围削弱场并持续吸噬",
	"mgd.drain": "噬魂",
	"mgd.drain.effect": "对削弱目标爆发并大幅吸血",
	"mgl.grace": "恩泽",
	"mgl.grace.effect": "圣光束普攻，微量自疗",
	"mgl.lightstep": "光步",
	"mgl.lightstep.effect": "瞬移并自我治疗/护盾",
	"mgl.ray": "圣光",
	"mgl.ray.effect": "光弹命中并自我祝福",
	"mgl.aegis": "光环",
	"mgl.aegis.effect": "自身 bless 脉冲",
	"mgl.faith": "信念",
	"mgl.faith.effect": "强化祝福持续与护盾",
	"mgl.dome": "光幕",
	"mgl.dome.effect": "展开减伤光幕",
	"mgl.smite": "惩戒",
	"mgl.smite.effect": "对敌光柱，对精英额外伤害",
	"mgl.holyshield": "圣盾",
	"mgl.holyshield.effect": "护盾破裂时反弹光弹",
	"mgl.rain": "光雨",
	"mgl.rain.effect": "区域落光并自我祝福",
	"mgl.field": "天域",
	"mgl.field.effect": "庇护场持续治疗与减伤",
	"mgl.purge": "净化",
	"mgl.purge.effect": "清除自身 debuff 并范围光爆",
	"skill.prereq_none": "无",
	"skill.prereq_item": "%s Lv%d",
	"skill.cd_none": "—",
	"skill.crystal_count": "晶核 %d",
	"skill.explorer_lv": "探索者 Lv.%d",
	"skill.next_cost": "感悟 -%d晶核",
	"skill.forget": "遗忘",
	"skill.forget_ok": "已遗忘：%s（退还 %d 晶核）",
	"skill.forget_innate": "天生技能至少保留 1 级",
	"skill.forget_prereq": "仍有后置技能依赖，无法遗忘",
	"skill.need_crystal": "晶核不足（需 %d）",
	"skill.need_prereq": "前置技能不足",
	"skill.max_rank": "已达满级",
	"skill.learn": "感悟",
	"skill.learn_ok": "已感悟：%s",
	"skill.learn_fail": "感悟失败",
	"skill.learn_hint": "晶核已进背包，回城感悟台可学习技能",
	"skill.need_level": "需要探索等级 %d",
	"skill.need_grade": "晶核品阶不足（需 %s）",
	"skill.need_mind": "念力值不足",
	"skill.need_rune": "没有该晶核",
	"skill.already": "已经感悟",
	"skill.pit_blocked": "只能在营地感悟台感悟",
	"skill.slot_locked": "侵蚀锁定了该技能槽",
	"skill.slot_empty": "该槽未装配技能（需先感悟并装配）",
	"menu.title": "巨坑之下",
	"menu.subtitle": "鹤城 · 深潜",
	"menu.continue": "继续游戏",
	"menu.new": "新游戏",
	"menu.load": "读取游戏",
	"menu.quit": "退出游戏",
	"menu.back": "返回",
	"menu.slot_empty": "空存档",
	"menu.slot_title": "存档 %d",
	"menu.slot_summary": "第 %d 日 · 探索等级 %d · 金币 %d",
	"menu.slot_time": "上次：%s",
	"menu.load_slot": "读取",
	"menu.delete_slot": "删除",
	"menu.use_slot": "开始",
	"menu.overwrite": "覆盖并开始",
	"menu.confirm_delete": "确定删除存档 %d？此操作不可恢复。",
	"menu.confirm_overwrite": "存档 %d 已有进度，确定覆盖？",
	"menu.confirm_yes": "确定",
	"menu.confirm_no": "取消",
	"menu.no_save": "尚无存档，请先开始新游戏",
	"menu.pick_new": "选择一个存档位开始新游戏",
	"menu.pick_load": "选择要读取或删除的存档",
	"menu.pick_imprint": "选择烙印，决定本档职业与技能树",
	"menu.pick_element": "元素分支",
	"menu.imprint_cold": "战痕烙印",
	"menu.imprint_hot": "鹰眼烙印",
	"menu.imprint_mage": "元素烙印",
	"menu.imprint_affinity": "亲和烙印",
	"menu.imprint_cold_desc": "近战力量，抗打与自愈",
	"menu.imprint_hot_desc": "弓弩矛，远程单体，身板脆",
	"menu.imprint_mage_desc": "自然元素清场，单体略弱",
	"menu.imprint_affinity_desc": "动物或植物召唤辅助，身板脆",
	"menu.imprint_pick": "选择",
	"menu.imprint_confirm": "以此烙印开始",
	"pause.title": "暂停",
	"pause.continue": "继续游戏",
	"pause.main_menu": "回到主界面",
	"pause.quit": "退出游戏",
	"pause.confirm_leave_run": "当前探索尚未撤离，返回主界面将中断本局。确定离开？",
	"pause.confirm_quit": "确定退出游戏？未撤离的探索将中断。",
	"skill.slot.rmb": "右键",
	"skill.slot.q": "Q",
	"skill.slot.e": "E",
	"skill.slot.r": "R",
	"skill.slot.f": "F",
	"skill.slot.c": "C",
	"skill.slot.basic": "普攻",
	"skill.slot.finisher": "杀招",
	"skill.slot.dodge": "闪避",
	"skill.slot.defend": "防御",
	"skill.slot.ultimate": "绝技",
	"skill.slot.passive": "被动",
	"core.s_chain": "连环斩核",
	"core.s_quake": "崩山击核",
	"core.s_dash": "踏锋核",
	"core.s_bolt": "刃气核",
	"core.s_whirl": "旋风核",
	"core.s_smash": "坑冠核",
	"core.a_toughbone": "韧骨核",
	"core.a_heavyarm": "沉臂核",
	"core.a_sharpeye": "锐眼核",
	"core.a_cruel": "狠劲核",
	"ws.bloodinstinct": "血战本能",
	"ws.bloodinstinct.effect": "被动。普攻命中回复 0.5% 最大生命；力量提高单次回复，上限 2%。",
	"ws.dashslash": "踏锋斩",
	"ws.dashslash.effect": "向鼠标方向突进 120 单位，斩击路径上首个敌人，造成 120% 物攻伤害。",
	"ws.heavyarm": "沉臂",
	"ws.heavyarm.effect": "被动。受到的所有伤害降低 4%，每阶额外降低 1%。",
	"ws.groundwave": "裂地波",
	"ws.groundwave.effect": "向前方 90°、半径 100 的扇形区域发动冲击，造成 150% 物攻伤害。",
	"ws.toughbone": "韧骨",
	"ws.toughbone.effect": "被动。受击硬直缩短 20%，造成的破韧提高 15%。",
	"ws.ironstance": "铁壁架势",
	"ws.ironstance.effect": "3 秒内减伤 40% 且无法移动；结束时震击周围，造成 80% 物攻伤害。",
	"ws.battlelust": "愈战愈勇",
	"ws.battlelust.effect": "被动。每损失 10% 最大生命，物攻提高 2%，最多提高 10%。",
	"ws.riposte": "反击之刃",
	"ws.riposte.effect": "开启 0.5 秒招架窗；成功后以 200% 物攻反击，并获得 0.5 秒无敌。",
	"ws.bloodthirst": "嗜血",
	"ws.bloodthirst.effect": "被动。击杀敌人回复 3% 最大生命，内置冷却 8 秒。",
	"ws.whirlwind": "旋风斩",
	"ws.whirlwind.effect": "在 1.2 秒内旋转三圈，每圈对周围敌人造成 80% 物攻伤害，期间移速降低 50%。",
	"ws.immovable": "不动如山",
	"ws.immovable.effect": "被动。站定 2 秒获得稳势：每层减伤 8%、物攻提高 5%，最多两层。",
	"ws.mountainbreak": "崩山击",
	"ws.mountainbreak.effect": "对前方单体发动 280% 物攻重击，造成双倍破韧。",
	"ws.ironskin": "铁肤",
	"ws.ironskin.effect": "被动。生命不高于 30% 时，额外减伤 15%。",
	"ws.warcry": "战吼",
	"ws.warcry.effect": "5 秒内减伤提高 20%、物攻提高 15%，并使周围敌人减速 15%。",
	"ws.scarheal": "战痕愈合",
	"ws.scarheal.effect": "被动。战斗中生命不高于 50% 时，每 3 秒回复 1.5% 最大生命。",
	"ws.chainassault": "连环追击",
	"ws.chainassault.effect": "在 1.5 秒内连续斩击五次，每段造成 65% 物攻伤害，段间可微调朝向。",
	"ws.breaksight": "破阵之眼",
	"ws.breaksight.effect": "被动。攻击已破防目标时，暴击率提高 12%、暴击伤害提高 15%。",
	"ws.shieldbreak": "破盾重击",
	"ws.shieldbreak.effect": "造成 320% 物攻伤害与 2.5 倍破韧；目标已破防时伤害再乘 1.5。",
	"ws.lethalfocus": "致命专注",
	"ws.lethalfocus.effect": "被动。攻击低韧性的精英或领主时，物攻提高 10%、破韧提高 20%。",
	"ws.desperaterush": "绝命突进",
	"ws.desperaterush.effect": "突进 200 单位并造成 320% 物攻伤害；自身生命不高于 40% 时伤害提高 25%。",
	"ws.laststand": "残躯",
	"ws.laststand.effect": "被动。受到致死伤害时保留 1 点生命，并在 2 秒内获得 50% 减伤；冷却 60 秒。",
	"ws.bloodrage": "血怒",
	"ws.bloodrage.effect": "消耗当前生命的 10%，8 秒内物攻提高 30%、命中吸血提高 15%。",
	"ws.veteran": "百战之躯",
	"ws.veteran.effect": "被动。力量与体力各提高 3 点，最大生命提高 5%。",
	"ws.cataclysm": "天崩地裂",
	"ws.cataclysm.effect": "跃起砸击目标点：中心造成 500% 物攻伤害，外围造成 250% 物攻伤害。",
	"ws.immortalscar": "不朽战痕",
	"ws.immortalscar.effect": "被动。所有生命回复提高 20%，缩短残躯冷却，并强化每场战斗首次终极大招。",
	"sk.chain": "连环斩",
	"sk.dash": "踏锋",
	"sk.bolt": "刃气",
	"sk.quake": "崩山击",
	"sk.stance": "刀势",
	"sk.riposte": "回斩",
	"sk.whirl": "旋风斩",
	"sk.ironwall": "铁壁",
	"sk.myriad": "千刃",
	"sk.smash": "坑冠碎",
	"sk.draw": "拔刀",
	"sk.chain.effect": "被动。强化普攻连段伤害与第二段起手速度。",
	"sk.dash.effect": "朝鼠标短冲并斩击路径上的敌人。",
	"sk.bolt.effect": "打出一道月牙刃气，可穿透。",
	"sk.quake.effect": "高举重劈，冲击波震开前方敌人。",
	"sk.stance.effect": "被动。提升物攻与攻速。",
	"sk.riposte.effect": "反向弧斩，出招瞬间短暂无敌。",
	"sk.whirl.effect": "原地旋斩，多段打击周围敌人。",
	"sk.ironwall.effect": "被动。降低受到的伤害（与觉醒铁壁乘算）。",
	"sk.myriad.effect": "三刀连斩，每一刀扇面不同。",
	"sk.smash.effect": "跃起砸向鼠标落点，裂地成环。",
	"sk.draw.effect": "收刀蓄势后横斩，超远距离一闪。",
	"nat.grove": "森息",
	"nat.leafstep": "叶步",
	"nat.thorn": "棘刺",
	"nat.whirl": "叶旋",
	"nat.grove.effect": "被动。强化召唤物，并缓慢回复生命。",
	"nat.leafstep.effect": "借叶风短冲，路径上甩出藤蔓。",
	"nat.thorn.effect": "射出穿透棘刺，命中留下毒藤。",
	"nat.whirl.effect": "周身叶旋，多段打击近身敌人。",
	"sk.chain.rank": "连斩伤害 +%d%%",
	"sk.stance.rank": "物攻 +%d%%，攻速 +%d%%",
	"sk.ironwall.rank": "受伤减免 %d%%",
	"mat.crystal_core": "晶核",
	"mat.crystal_core.desc": "坑中凝结的感悟结晶。回城感悟台消耗后可学习烙印技能。",
	"core.s_chain.effect": "强化普攻连段与伤害（被动）",
	"core.s_quake.effect": "朝鼠标方向砸地高伤",
	"core.s_dash.effect": "短冲向鼠标（无无敌帧）",
	"core.s_bolt.effect": "朝鼠标射出刃气",
	"core.s_whirl.effect": "身周范围斩击",
	"core.s_smash.effect": "鼠标落点大范围砸击",
	"core.a_toughbone.effect": "体力与生命小幅提升",
	"core.a_heavyarm.effect": "力量与物攻小幅提升",
	"core.a_sharpeye.effect": "暴击小幅提升",
	"core.a_cruel.effect": "爆伤小幅提升",
	"stat.explorer_lv": "探索等级",
	"stat.explorer_xp": "经验",
	"hud.xp": "探索 %d 级  XP %d/%d",
	"hud.xp_bar": "%d级  %d/%d  %d%%",
	"pickup.core": "获得晶核：%s x%d",
	"pickup.core_skill": "获得技能晶核：%s x%d",
	"pickup.core_attr": "获得属性晶核：%s x%d",
	"toast.xp": "+%d 经验",
	"toast.levelup": "探索等级提升至 %d",
	"facility.comprehend": "感悟台·技能树",
	"hud.interact_comprehend": "[空格] 感悟台",
	"facility.dummy": "试刀桩",
	"hud.interact_dummy": "[空格] 试刀桩",
	"hub.enter_dummy": "进入试刀场：可放技能、随意调整等级。离开后还原存档加点，不消耗晶核、不入坑。",
	"hub.enter_training": "进入试刀场",
	"hud.interact_return_hub": "[空格] 返回鹤城",
	"training.sandbox_hint": "试刀场 · 等级不写盘",
	"training.rank_plus": "+1",
	"training.rank_minus": "-1",
	"training.max_all": "全部满级",
	"training.restore": "恢复存档加点",
	"training.return_hub": "返回鹤城",
	"training.open_skills": "技能树 (K)",
	"training.panel_title": "试刀场·技能",
	"rune.s_chain": "连环斩",
	"rune.s_quake": "崩山击",
	"rune.s_cloudstep": "踏云",
	"rune.s_ironwall": "铁壁",
	"rune.a_toughbone": "韧骨",
	"rune.a_heavyarm": "沉臂",
	"rune.a_sharpeye": "锐眼",
	"rune.a_cruel": "狠劲",
	"rune.s_chain.effect": "强化普攻连段与伤害",
	"rune.s_quake.effect": "强化杀招伤害",
	"rune.s_cloudstep.effect": "缩短闪避冷却",
	"rune.s_ironwall.effect": "按住 Ctrl 减伤（需先学习）",
	"rune.a_toughbone.effect": "体力与生命小幅提升",
	"rune.a_heavyarm.effect": "力量与物攻小幅提升",
	"rune.a_sharpeye.effect": "暴击小幅提升",
	"rune.a_cruel.effect": "爆伤小幅提升",
	"extract.brand_lost": "已学技能保留",
	"extract.skills_kept": "已学技能保留",
	"extract.death_keep_all": "背包物资已全部带回鹤城。",
	"extract.death_wear": "探索等级 3 起，死亡会磨损胸甲与挂坠。",
	"item.mat_tip": "%s\n品阶：%s\n数量：%d\n%s",
	"item.rune_tip": "%s\n品阶：%s\n%s",
	"item.tier_name": "[%s] %s",
	"tier.common": "普通",
	"tier.uncommon": "精良",
	"tier.rare": "稀有",
	"tier.epic": "传说",
	"tier.legendary": "史诗",
	"tier.mythic": "神话",
	"grade.1": "九品",
	"grade.2": "八品",
	"grade.3": "七品",
	"grade.4": "六品",
	"grade.5": "五品",
	"grade.6": "四品",
	"grade.7": "三品",
	"grade.8": "二品",
	"grade.9": "一品",
	"item.grade_quality_name": "[%s·%s] %s",
	"hud.hp": "生命 %d/%d",
	"hud.erosion_value": "侵蚀 %d/%d",
	"hud.erosion_tier_short": "侵蚀 %d 档",
	"hud.status.erosion": "侵蚀 %d 档",
	"hud.status.mud": "泥沼减速",
	"hud.status.fog": "雾隐",
	"hud.status.metal": "磁累",
	"hud.status.lock": "技能锁定",
	"hud.status.heavy": "超重",
	"hud.status.erosion.tip1": "深渊侵蚀 1 档。\n伤害与移速正常，侵蚀仍在加速累积。",
	"hud.status.erosion.tip2": "深渊侵蚀 2 档。\n伤害略降，移速 -8%，负重 +15%。",
	"hud.status.erosion.tip3": "深渊侵蚀 3 档。\n伤害降低，移速 -15%，负重 +15%。\n锁定 1 个已装配技能槽，并持续掉血。",
	"hud.status.mud.tip": "潮腐泥沼。\n移速降至约 55%，离开泥地后恢复。",
	"hud.status.fog.tip": "隐身于雾中。\n敌人警戒降低，更难被发现。",
	"hud.status.metal.tip": "折铜谷·磁累。\n金属负重使移速下降、技能冷却变长。\n卸下金属件或离开本区可减轻。",
	"hud.status.lock.tip": "侵蚀锁定了 1 个已装配技能槽。\n该槽无法释放，直至侵蚀下降或撤离。",
	"hud.status.heavy.tip": "背包超重。\n无法再拾取物品，需丢弃部分物资或撤离。",
	"hud.runes": "符文",
	"hud.bag": "背包 %d/%d",
	"hud.floor": "第 %d 层",
	"hud.brand": "烙印：%s",
	"hud.region": "区域：%s",
	"hud.region_enter": "进入 — %s",
	"hud.special_mind_yes": "特殊念力：已持有",
	"hud.special_mind_no": "特殊念力：无",
	"hud.gold": "金币 %d",
	"hud.paper_notes": "金币券 %d",
	"hud.game_day": "第 %d 日",
	"hud.pit_ready_today": "今日可入坑",
	"hud.pit_done_today": "今日已入坑",
	"hud.pit_open": "可随时入坑",
	"hub.enter_pit_free": "入坑无每日次数限制。",
	"hud.mind": "念力 %d 级",
	"hud.mind_value": "念力值 %d",
	"hud.quest": "委托：%s",
	"hud.quest_none": "委托：无",
	"hud.quest_progress": "%s  %s",
	"hud.quest_done": "（可撤离结算）",
	"hud.quest_btn": "委托",
	"hud.quest_panel_title": "任务看板",
	"hud.quest_detail": "%s\n进度：%s%s\n\n%s\n\n%s",
	"hud.map_title": "地图",
	"toast.extract_hint": "每区撤离点旁与野外各有传送；小地图「撤」「传」可指引",
	"map.poi_extract": "撤",
	"map.poi_secret": "秘",
	"map.poi_warp": "传",
	"map.poi_npc": "救",
	"map.poi_descent": "下",
	"map.poi_boss": "王",
	"map.node_hidden": "？",
	"map.node_blocked": "封",
	"map.peek_hint": "探照灯预览",
	"map.type_combat": "战斗",
	"map.type_resource": "资源",
	"map.type_elite": "精英",
	"map.type_event": "事件",
	"map.type_extract": "撤离",
	"map.type_boss": "BOSS",
	"map.type_warp": "传送",
	"map.type_shortcut": "捷径",
	"map.type_quest": "委托",
	"map.type_descent": "下层",
	"hud.quest_none_detail": "当前没有进行中的委托。\n可在鹤城任务看板接取。",
	"hud.interact_extract": "[空格] 启动撤离信标 · 回营",
	"hud.extract_marker": "撤离口",
	"hud.btn_extract": "撤离回营",
	"hud.door_forward": "前进 ›",
	"hud.door_back": "‹ 返回",
	"hud.door_to_extract": "› 撤离点",
	"hud.interact_descent": "[空格] 下层入口",
	"hud.interact_descent_locked": "[空格] 下层入口（需特殊念力）",
	"hud.interact_descent_ready": "[空格] 检视下层入口",
	"hud.interact_warp": "[空格] 传送点",
	"hud.interact_warp_locked": "[空格] 未激活的传送点",
	"hud.interact_warp_named": "[空格] %s",
	"hud.interact_warp_locked_named": "[空格] 未激活 · %s",
	"hud.extract_world": "撤离点",
	"hud.interact_forage": "[空格] 采集",
	"hud.interact_ore": "[空格] 挖矿",
	"hud.interact_chest": "[空格] 打开炼金匣",
	"hud.interact_pickup": "[空格] 拾取",
	"hud.interact_distress": "[空格] 启动求救信标",
	"region.a": "沉苔沼",
	"region.b": "折铜谷",
	"region.c": "盲灯廊",
	"region.boss": "层主之域",
	"region.spawn": "入坑安全区",
	"warp.a": "沉苔沼·撤离传送",
	"warp.a2": "沉苔沼·野外传送",
	"warp.b": "折铜谷·撤离传送",
	"warp.b2": "折铜谷·野外传送",
	"warp.c": "盲灯廊·撤离传送",
	"warp.c2": "盲灯廊·野外传送",
	"warp.warp_a": "沉苔沼·撤离传送",
	"warp.warp_a2": "沉苔沼·野外传送",
	"warp.warp_b": "折铜谷·撤离传送",
	"warp.warp_b2": "折铜谷·野外传送",
	"warp.warp_c": "盲灯廊·撤离传送",
	"warp.warp_c2": "盲灯廊·野外传送",
	"warp.need_guard": "需击杀看守方可激活",
	"warp.unlocked": "传送点已激活：%s",
	"warp.menu_title": "区域传送",
	"warp.menu_hint": "消耗念力值 %d（库存 %d）",
	"warp.travel_to": "传往 %s",
	"warp.no_other": "没有其它已激活传送点",
	"warp.no_mind": "念力值不足",
	"warp.traveled": "已传送至 %s",
	"descent.need_mind": "需要击败层 BOSS 取得特殊念力",
	"descent.locked_mvp": "更深之径尚未开启",
	"extract.special_mind_lost": "特殊念力已消散（局内不保留）",
	"mat.mire_pearl": "沼珠",
	"mat.fold_copper": "折铜片",
	"mat.blind_wick": "盲灯芯",
	"mat.lamp_oil_crystal": "灯油晶",
	"mat.mire_pearl.desc": "沉苔沼凝珠，炼金触媒。",
	"mat.fold_copper.desc": "折铜谷薄铜片，机关与烙印相关。",
	"mat.blind_wick.desc": "盲灯廊灯芯残段。",
	"mat.lamp_oil_crystal.desc": "凝固灯油结晶，照明与念力相关。",
	"quest.gather_ore.name": "折铜谷采赤矿",
	"quest.gather_ore.desc": "于折铜谷带回 3 份深赤矿并成功撤离。",
	"quest.kill_scale.name": "猎杀沉苔沼鳞岩兽",
	"quest.kill_scale.desc": "于沉苔沼击杀 2 只鳞岩兽并成功撤离。",
	"quest.rescue.name": "盲灯廊救援",
	"quest.rescue.desc": "于盲灯廊启动求救信标并成功撤离。",
	"hub.enter_pit": "确认进入巨坑第 1 层？本局将生成烙印。",
	"hub.enter": "默认出生入坑",
	"hub.enter_warp": "传送出生（-%d 念力值）",
	"hub.enter_warp_need": "选择已解锁传送点出生",
	"hub.warp_option": "%s（已解锁）",
	"hub.warp_locked_none": "尚无已解锁传送点",
	"hub.mind_value_line": "念力值：%d / %d（休息回满）",
	"hud.interact_e": "[空格] %s",
	"hud.interact_board": "[空格] 告示板",
	"hud.interact_alchemy": "[空格] 炼金台",
	"hud.interact_quiet": "[空格] 静室",
	"hud.interact_inn": "[空格] 旅店",
	"hud.interact_exchange": "[空格] 兑换所",
	"hud.interact_pit": "[空格] 进入巨坑",
	"hud.interact_stash": "[空格] 查看仓库",
	"facility.board": "告示板",
	"facility.alchemy": "炼金台",
	"facility.quiet": "静室",
	"facility.inn": "旅店",
	"facility.exchange": "兑换所",
	"facility.stash": "材料仓库",
	"facility.pit": "巨坑入口",
	"hud.room_combat": "战斗室",
	"hud.room_resource": "资源室",
	"hud.room_elite": "精英室",
	"hud.room_extract": "撤离室",
	"hud.room_start": "入口",
	"hud.room_descent": "下潜室",
	"hud.runes_none": "尚无已学技能",
	"brand.iron": "铁纹",
	"brand.copper": "铜纹",
	"brand.silver": "银纹",
	"brand.gold": "金纹",
	"mat.glow_moss": "荧苔",
	"mat.bitter_root": "苦根",
	"mat.deep_red_ore": "深赤矿",
	"mat.copper_vein": "铜纹矿",
	"mat.mind_shard": "念力碎晶",
	"mat.mind_core": "念核残片",
	"mat.beast_scale": "兽鳞片",
	"mat.chitin_plate": "甲壳碎片",
	"mat.alchem_slag": "炼渣锭",
	"mat.ember_gland": "灼腺",
	"mat.glow_moss.desc": "微光苔藓，炼金与照明常用。",
	"mat.bitter_root.desc": "苦涩药根，静室与药剂底料。",
	"mat.deep_red_ore.desc": "深坑赤矿，强化与熔炼原料。",
	"mat.copper_vein.desc": "带铜纹的矿脉碎片，烙印相关。",
	"mat.mind_shard.desc": "碎裂的念力结晶，静室吸收用。",
	"mat.mind_core.desc": "更纯粹的念核残片，高效升念。",
	"mat.beast_scale.desc": "坑兽鳞片，护甲与炼渣原料。",
	"mat.chitin_plate.desc": "甲壳碎片，坚硬耐磨。",
	"mat.alchem_slag.desc": "炼金残渣锭，万能合成材料。",
	"mat.ember_gland.desc": "灼热腺体，火性炼金素材。",
	"equip.chest": "胸甲",
	"equip.amulet": "挂坠",
	"equip.not_owned": "未打造",
	"equip.owned": "强化%+d（磨损%d）",
	"equip.stats": "生命+%.0f 防御+%.0f 伤害+%.0f%%",
	"extract.title": "撤离成功",
	"extract.fail_title": "探索失败",
	"extract.materials": "带回材料",
	"extract.runes_lost": "符文与烙印已消散（局内不保留）",
	"extract.empty": "（空空如也）",
	"extract.keep_one": "请选择保留的 1 格材料：",
	"extract.confirm_keep": "确认带回",
	"extract.back_hub": "返回鹤城",
	"extract.retry": "再次入坑",
	"extract.arena": "返回试刀场",
	"extract.quest_ok": "委托完成，已发放奖励",
	"extract.quest_fail": "委托失败",
	"pickup.rune": "获得符文：%s",
	"pickup.mat": "获得：%s x%d",
	"feed.kill": "击杀 %s",
	"feed.kill_elite": "击杀精英 %s",
	"feed.kill_boss": "击败 %s",
	"bag.full": "背包已满",
	"enemy.pit_grub": "坑蛆",
	"enemy.scale_rock": "鳞岩兽",
	"enemy.a_moss_grub": "苔沼蛆",
	"enemy.a_spore": "孢喷虫",
	"enemy.a_scale": "鳞岩兽",
	"enemy.b_mite": "铜螨",
	"enemy.b_beetle": "锈甲虫",
	"enemy.b_slag": "炉渣喷吐者",
	"enemy.c_wisp": "灯焰鬼火",
	"enemy.c_grub": "影沼蛆",
	"enemy.c_shell": "灯笼壳虫",
	"enemy.elite_a": "沼域领主",
	"enemy.special_a": "沼渊畸种",
	"secret.door_prompt": "[空格] 进入秘境深坑（需击杀沼域领主或持有沼珠）",
	"secret.mouth_prompt": "[空格] 进入秘境深坑（需击杀沼域领主或持有沼珠）",
	"secret.need_condition": "秘境未开：击败沉苔沼精英，或持有沼珠",
	"secret.opened": "坠入苔渊秘境…",
	"secret.exit_prompt": "[空格] 离开秘境，返回巨坑",
	"secret.mire_hint": "WASD 移动 | 左键普攻 | 空格交互洞口/宝箱 | Tab 背包\n苔渊秘境 — 击杀畸种、搜刮宝箱后从洞口返回",
	"secret.mire_title": "苔渊秘境",
	"secret.chest_prompt": "[空格] 打开秘境宝箱",
	"secret.chest_loot": "秘境宝箱：%s",
	"secret.chest_gold": "金币 +%d",
	"enemy.elite_b": "折铜典狱",
	"enemy.elite_c": "盲灯守者",
	"enemy.guard_a": "传送看守·甲",
	"enemy.guard_b": "传送看守·乙",
	"enemy.guard_c": "传送看守·丙",
	"enemy.boss_floor1": "层主·坑冠",
	"enemy.side_melee": "苔刺甲虫",
	"enemy.side_ranged": "孢囊射手",
	"enemy.side_flyer": "沼灯游蝇",
	"enemy.side_elite": "沼域领卫",
	"enemy.side_boss": "坑冠兽",
	"hud.boss_name": "BOSS",
	"sfx.blade_hit": "[音效] 刀刃命中",
	"dummy.reset": "[木桩] 已重置",
	"dummy.hit": "[木桩] 受到 %.0f 伤害，生命 %.0f",
	"smoke.hp_light": "[冒烟测试] 轻斩后木桩生命 = %s",
	"smoke.hp_heavy": "[冒烟测试] 重击后木桩生命 = %s",
	"hub.title": "鹤城 · 炼金补给站",
	"hub.close": "关闭",
	"hub.board_title": "任务看板",
	"hub.accept": "接取",
	"hub.abandon": "放弃委托",
	"hub.quest_busy": "已有进行中的委托",
	"hub.quest_accepted": "已接取：%s",
	"hub.quest_active": "进行中：%s",
	"hub.quest_target": "进度目标：%s（入坑后实时计数）",
	"hub.quest_progress_hint": "坑内右上角可查看实时进度与详情。",
	"hub.quiet_title": "静室 · 念力等级",
	"hub.quiet_level": "当前念力等级：%d / 5",
	"hub.quiet_value_cap": "念力值储备：%d / %d（休息回满）",
	"hub.quiet_cost": "升级需等效碎晶 %d 个｜库存：碎晶 %d + 念核 %d（×3）= 共 %d",
	"hub.quiet_effect_desc": "升级后：念力上限 +%d，烙印品质概率提升",
	"hub.quiet_weights_now": "当前烙印：铁 %d%% · 铜 %d%% · 银 %d%% · 金 %d%%",
	"hub.quiet_weights_next": "升级后烙印：铁 %d%% · 铜 %d%% · 银 %d%% · 金 %d%%",
	"hub.quiet_do": "消耗材料升至 %d 级",
	"hub.quiet_ok": "念力提升至 %d 级",
	"hub.quiet_max": "念力等级已满",
	"hub.quiet_no": "碎晶或念核不足",
	"hub.inn_title": "旅店 · 休息 / 抗蚀",
	"hub.inn_body": "第 %d 日。当前念力值 %d / %d。\n休息将推进至下一日并回满念力值。",
	"hub.inn_shop_line": "清蚀药 %d 金（降侵蚀）｜抗蚀香囊 %d 金（本局侵蚀增速再减半）\n购入后入仓库，进坑时自动带入背包使用。",
	"hub.inn_rest": "休息（次日）",
	"hub.inn_ok": "已休息，进入第 %d 日",
	"hub.inn_buy_salve": "清蚀药 %d金",
	"hub.inn_buy_ward": "抗蚀香囊 %d金",
	"hub.buy_salve_ok": "清蚀药已入仓库",
	"hub.buy_ward_ok": "抗蚀香囊已入仓库",
	"hub.exchange_title": "兑换所",
	"hub.exchange_hint": "金币换券：%d 金 → 1 金币券（减重）\n金币券兑回 / 购物折算：1 张 = %d 金（购买时自动扣券，无需先兑成金币）",
	"hub.exchange_potion_line": "念力药剂：%d 金 / 瓶（恢复 %d 念力值；可用金币券折算）",
	"hub.spendable_gold": "可支付合计：%d 金（含券折算）",
	"hub.exchange_gold_to_paper": "换金币券 %d金",
	"hub.exchange_paper_to_gold": "兑金币 %d",
	"hub.buy_mind_potion": "买药剂 %d金",
	"hub.exchange_gold_ok": "已兑换 1 张金币券",
	"hub.exchange_paper_ok": "已兑回金币",
	"hub.buy_potion_ok": "念力药剂已入仓库",
	"hub.no_gold": "金币与金币券合计不足",
	"hub.no_paper": "金币券不足",
	"hub.pit_blocked": "今日已入坑，请至旅店休息后再试",
	"hub.sell_one": "出售选中 1 份",
	"hub.sell_ok": "出售 %s，+%d 金币",
	"hub.sell_none": "请先选中要出售的材料",
	"hub.sell_not_material": "只能出售材料",
	"hub.sell_crystal_locked": "晶核不能出售，请到感悟台学习技能",
	"hub.sell_fail": "出售失败",
	"hub.alchemy_title": "炼金台 · 打造强化",
	"hub.craft": "打造",
	"hub.upgrade": "强化",
	"hub.craft_ok": "打造完成：%s",
	"hub.upgrade_ok": "强化成功：%s",
	"hub.craft_cost": "打造需：%s",
	"hub.upgrade_cost": "强化需：%s",
	"hub.cost_lack": "（不足）",
	"hub.no_mats": "材料不足",
	"hub.stash_title": "材料仓库",
	"hub.stash_empty": "仓库空空如也",
	"hub.stash_sell_hint": "点击格子选中材料，再按「出售」",
	"hub.owned_toast": "已拥有",
	"hub.abandon_toast": "已放弃委托",
	"quest.reward": "奖励：金币 %d；%s",
	"quest.reward_mats_none": "无额外材料",
	"intel.floor_cleared": "记录：曾从第 %d 层成功撤离。",
	"biome.moss": "沉苔沼",
	"biome.copper": "折铜谷",
	"biome.echo": "盲灯廊",
	"biome.rule.moss": "潮腐：泥沼减速，雾中降警戒",
	"biome.rule.copper": "磁累：金属件越多移速/技能冷却越差",
	"biome.rule.echo": "回声：杀招吸引增援",
	"hud.interact_door": "[空格] 前往相邻段落",
	"hud.interact_gather": "[空格] 采集",
	"hud.interact_shortcut": "[空格] 激活地脉捷径",
	"hud.interact_rescue": "[空格] 标记救援",
	"hud.interact_generic": "[空格] 交互",
	"toast.shortcut_armed": "捷径已记录，成功撤离后跨局生效",
	"toast.descent_locked_mvp": "更深之径尚未开放（MVP）",
	"toast.need_special_mind": "需要层 BOSS 特殊念力",
	"toast.rescue_done": "已完成标记救援",
	"toast.breath_blocked": "吐息封锁了此节点",
	"toast.warp_unlocked": "传送锚点已激活",
	"toast.warp_need_guard": "需先击败看守",
	"toast.warp_only_one": "暂无其它已激活锚点",
	"toast.no_mind": "念力值不足",
	"toast.event_minor": "坑底低语……并无大事",
	"toast.erosion_tier": "深渊侵蚀升至第 %d 档",
	"toast.echo_reinforce": "回声引来增援！",
	"settle.success_title": "撤离成功",
	"settle.success_body": "物资已入仓。委托结算：%s",
	"settle.death_title": "阵亡",
	"settle.death_body": "物资已全部带回鹤城（装备可能磨损）",
	"settle.death_empty": "背包空空，直接返回营地",
	"settle.death_pick": "保留 [%d/%d]：%s x%d",
	"settle.cycle_keep": "切换下一格",
	"settle.confirm_keep": "确认保留此格",
	"settle.death_hint": "A/D 切换保留格",
	"hub.winch_title": "绞盘机",
	"hub.winch_body": "等级 %d/3\n提升负重与抗磁累移速。\n升级需：%s",
	"hub.winch_ok": "绞盘机升至 %d 级",
	"hub.spotlight_title": "探照灯",
	"hub.spotlight_body": "等级 %d/3\n提前揭示相邻迷雾。\n升级需：%s\n吐息：%s",
	"hub.spotlight_ok": "探照灯升至 %d 级",
	"hub.breath_active": "今日吐息活跃（资源节点封锁 + 吐息精英）",
	"hub.breath_idle": "今日平静",
	"hub.infra_max": "已达最高等级",
	"hub.awaken_title": "武器觉醒台",
	"hub.awaken_body": "当前分支：%s\n旋风锋需：%s\n铁壁反需：%s\n（每把大刀仅一条觉醒）",
	"hub.awaken_ok": "觉醒完成：%s",
	"hub.awaken_owned": "已觉醒该分支",
	"hub.awaken_locked": "已选择另一觉醒分支",
	"awaken.none": "未觉醒",
	"awaken.whirl": "旋风锋",
	"awaken.ironwall": "铁壁反",
	"mat.whirl_edge": "旋风锋胚",
	"mat.iron_guard": "铁壁反胚",
}


func t(key: String, args: Array = []) -> String:
	var text: String = str(_strings.get(key, key))
	if args.is_empty():
		return text
	return text % args


func has_key(key: String) -> bool:
	return _strings.has(key)
