extends Node
## Autoload：全局中文。用 Loc.t("key")。

var _strings: Dictionary = {
	"hint.combat_arena": "WASD 移动 | 鼠标瞄准 | 左键轻斩 | 右键重击 | 空格翻滚\n阶段 A — 大刀手感原型",
	"hint.pit_floor": "WASD 移动 | 鼠标瞄准 | 左键轻斩 | 右键重击 | 空格翻滚 | E 交互 | Q 切换目标 | Tab/B 背包",
	"hud.interact_pickup_named": "[E] 拾取 %s",
	"hud.interact_multi": "%s  · Q切换（%d/%d）",
	"hud.bag_btn": "背包",
	"hud.bag_title": "探索背包",
	"hud.bag_close": "关闭（Tab）",
	"item.mat_tip": "%s\n品阶：%s\n数量：%d\n%s",
	"item.rune_tip": "%s\n品阶：%s\n%s",
	"item.tier_name": "[%s] %s",
	"tier.common": "普通",
	"tier.uncommon": "精良",
	"tier.rare": "稀有",
	"tier.epic": "史诗",
	"tier.legendary": "传说",
	"rune.replace_hint": "符文槽已满，请选择要替换的符文",
	"rune.replace_title": "替换符文",
	"rune.replaced": "已装备：%s",
	"rune.max_rank": "该符文已达最高阶",
	"hint.hub": "WASD 移动 | E 交互设施\n鹤城枢纽 — 接委托 / 念力 / 打造 / 入坑",
	"hud.hp": "生命 %d/%d",
	"hud.runes": "符文",
	"hud.bag": "背包 %d/%d",
	"hud.floor": "第 %d 层",
	"hud.brand": "烙印：%s",
	"hud.region": "区域：%s",
	"hud.region_enter": "进入 — %s",
	"hud.special_mind_yes": "特殊念力：已持有",
	"hud.special_mind_no": "特殊念力：无",
	"hud.gold": "金币 %d",
	"hud.mind": "念力 %d 级",
	"hud.mind_value": "念力值 %d",
	"hud.quest": "委托：%s",
	"hud.quest_none": "委托：无",
	"hud.quest_progress": "%s  %s",
	"hud.quest_done": "（可撤离结算）",
	"hud.quest_btn": "委托",
	"hud.quest_panel_title": "任务看板",
	"hud.quest_detail": "%s\n进度：%s%s\n\n%s\n\n%s",
	"hud.map_title": "地图",
	"hud.quest_none_detail": "当前没有进行中的委托。\n可在鹤城任务看板接取。",
	"hud.interact_extract": "[E] 启动撤离信标",
	"hud.interact_descent": "[E] 下层入口",
	"hud.interact_descent_locked": "[E] 下层入口（需特殊念力）",
	"hud.interact_descent_ready": "[E] 检视下层入口",
	"hud.interact_warp": "[E] 传送点",
	"hud.interact_warp_locked": "[E] 未激活的传送点",
	"hud.interact_forage": "[E] 采集",
	"hud.interact_ore": "[E] 挖矿",
	"hud.interact_chest": "[E] 打开炼金匣",
	"hud.interact_pickup": "[E] 拾取",
	"hud.interact_distress": "[E] 启动求救信标",
	"region.a": "沉苔沼",
	"region.b": "折铜谷",
	"region.c": "盲灯廊",
	"region.boss": "层主之域",
	"region.spawn": "入坑安全区",
	"warp.a": "沉苔沼传送点",
	"warp.b": "折铜谷传送点",
	"warp.c": "盲灯廊传送点",
	"warp.need_guard": "需击杀看守方可激活",
	"warp.unlocked": "传送点已激活：%s",
	"warp.menu_title": "区域传送",
	"warp.menu_hint": "消耗念力值 %d（库存 %d）",
	"warp.travel_to": "传往 %s",
	"warp.no_other": "没有其它已激活传送点",
	"warp.no_mind": "念力值不足",
	"warp.traveled": "已传送至 %s",
	"descent.need_mind": "需要击败层 BOSS 取得特殊念力",
	"descent.locked_mvp": "更深之径尚未开启",
	"extract.special_mind_lost": "特殊念力已消散（局内不保留）",
	"mat.mire_pearl": "沼珠",
	"mat.fold_copper": "折铜片",
	"mat.blind_wick": "盲灯芯",
	"mat.lamp_oil_crystal": "灯油晶",
	"mat.mire_pearl.desc": "沉苔沼凝珠，炼金触媒。",
	"mat.fold_copper.desc": "折铜谷薄铜片，机关与烙印相关。",
	"mat.blind_wick.desc": "盲灯廊灯芯残段。",
	"mat.lamp_oil_crystal.desc": "凝固灯油结晶，照明与念力相关。",
	"quest.gather_ore.name": "折铜谷采赤矿",
	"quest.gather_ore.desc": "于折铜谷带回 3 份深赤矿并成功撤离。",
	"quest.kill_scale.name": "猎杀沉苔沼鳞岩兽",
	"quest.kill_scale.desc": "于沉苔沼击杀 2 只鳞岩兽并成功撤离。",
	"quest.rescue.name": "盲灯廊救援",
	"quest.rescue.desc": "于盲灯廊启动求救信标并成功撤离。",
	"hub.enter_pit": "确认进入巨坑第 1 层？本局将生成烙印。",
	"hub.enter": "默认出生入坑",
	"hub.enter_warp": "传送出生（-%d 念力值）",
	"hub.enter_warp_need": "选择已解锁传送点出生",
	"hub.warp_option": "%s（已解锁）",
	"hub.warp_locked_none": "尚无已解锁传送点",
	"hub.quiet_convert": "转化为念力值",
	"hub.quiet_convert_ok": "念力值 +%d（当前 %d）",
	"hub.mind_value_line": "念力值库存：%d（碎晶→%d / 核→%d）",
	"hud.interact_e": "[E] %s",
	"hud.interact_board": "[E] 告示板",
	"hud.interact_alchemy": "[E] 炼金台",
	"hud.interact_quiet": "[E] 静室",
	"hud.interact_pit": "[E] 进入巨坑",
	"hud.interact_stash": "[E] 查看仓库",
	"facility.board": "告示板",
	"facility.alchemy": "炼金台",
	"facility.quiet": "静室",
	"facility.stash": "材料仓库",
	"facility.pit": "巨坑入口",
	"hud.room_combat": "战斗室",
	"hud.room_resource": "资源室",
	"hud.room_elite": "精英室",
	"hud.room_extract": "撤离室",
	"hud.room_start": "入口",
	"hud.room_descent": "下潜室",
	"hud.runes_none": "无",
	"hud.rune_line": "%s %d阶 — %s",
	"rune.tough": "韧皮",
	"rune.swift": "疾步",
	"rune.slash": "迅斩",
	"rune.sidestep": "侧身",
	"rune.edge": "锋刃",
	"rune.reach": "延斩",
	"rune.burn": "灼痕",
	"rune.quake": "崩山",
	"rune.tough.effect": "最大生命 +20/阶",
	"rune.swift.effect": "移速 +8%/阶",
	"rune.slash.effect": "攻速 +8%/阶",
	"rune.sidestep.effect": "翻滚冷却 −8%/阶",
	"rune.edge.effect": "伤害 +12%/阶",
	"rune.reach.effect": "攻击距离 +8%/阶",
	"rune.burn.effect": "灼烧 4/阶 每秒",
	"rune.quake.effect": "重击伤害 +15%/阶，击退 +12%/阶",
	"brand.iron": "铁纹",
	"brand.copper": "铜纹",
	"brand.silver": "银纹",
	"brand.gold": "金纹",
	"mat.glow_moss": "荧苔",
	"mat.bitter_root": "苦根",
	"mat.deep_red_ore": "深赤矿",
	"mat.copper_vein": "铜纹矿",
	"mat.mind_shard": "念力碎晶",
	"mat.mind_core": "念核残片",
	"mat.beast_scale": "兽鳞片",
	"mat.chitin_plate": "甲壳碎片",
	"mat.alchem_slag": "炼渣锭",
	"mat.ember_gland": "灼腺",
	"mat.glow_moss.desc": "微光苔藓，炼金与照明常用。",
	"mat.bitter_root.desc": "苦涩药根，静室与药剂底料。",
	"mat.deep_red_ore.desc": "深坑赤矿，强化与熔炼原料。",
	"mat.copper_vein.desc": "带铜纹的矿脉碎片，烙印相关。",
	"mat.mind_shard.desc": "碎裂的念力结晶，静室吸收用。",
	"mat.mind_core.desc": "更纯粹的念核残片，高效升念。",
	"mat.beast_scale.desc": "坑兽鳞片，护甲与炼渣原料。",
	"mat.chitin_plate.desc": "甲壳碎片，坚硬耐磨。",
	"mat.alchem_slag.desc": "炼金残渣锭，万能合成材料。",
	"mat.ember_gland.desc": "灼热腺体，火性炼金素材。",
	"equip.chest": "胸甲",
	"equip.amulet": "挂坠",
	"equip.not_owned": "未打造",
	"equip.owned": "强化 %+d（磨损 %d）",
	"equip.stats": "生命+%.0f 防御+%.0f 伤害+%.0f%%",
	"extract.title": "撤离成功",
	"extract.fail_title": "探索失败",
	"extract.materials": "带回材料",
	"extract.runes_lost": "符文与烙印已消散（局内不保留）",
	"extract.empty": "（空空如也）",
	"extract.keep_one": "请选择保留的 1 格材料：",
	"extract.confirm_keep": "确认带回",
	"extract.back_hub": "返回鹤城",
	"extract.retry": "再次入坑",
	"extract.arena": "返回试刀场",
	"extract.quest_ok": "委托完成，已发放奖励",
	"extract.quest_fail": "委托失败",
	"pickup.rune": "获得符文：%s",
	"pickup.mat": "获得：%s x%d",
	"feed.kill": "击杀 %s",
	"feed.kill_elite": "击杀精英 %s",
	"feed.kill_boss": "击败 %s",
	"bag.full": "背包已满",
	"rune.slots_full": "符文槽已满，无法装备",
	"rune.upgraded": "%s 升至 %d 阶",
	"enemy.pit_grub": "坑蛆",
	"enemy.scale_rock": "鳞岩兽",
	"enemy.a_moss_grub": "苔沼蛆",
	"enemy.a_spore": "孢喷虫",
	"enemy.a_scale": "鳞岩兽",
	"enemy.b_mite": "铜螨",
	"enemy.b_beetle": "锈甲虫",
	"enemy.b_slag": "炉渣喷吐者",
	"enemy.c_wisp": "灯焰鬼火",
	"enemy.c_grub": "影沼蛆",
	"enemy.c_shell": "灯笼壳虫",
	"enemy.elite_a": "沼域领主",
	"enemy.elite_b": "折铜典狱",
	"enemy.elite_c": "盲灯守者",
	"enemy.guard_a": "传送看守·甲",
	"enemy.guard_b": "传送看守·乙",
	"enemy.guard_c": "传送看守·丙",
	"enemy.boss_floor1": "层主·坑冠",
	"sfx.blade_hit": "[音效] 刀刃命中",
	"dummy.reset": "[木桩] 已重置",
	"dummy.hit": "[木桩] 受到 %.0f 伤害，生命 %.0f",
	"smoke.hp_light": "[冒烟测试] 轻斩后木桩生命 = %s",
	"smoke.hp_heavy": "[冒烟测试] 重击后木桩生命 = %s",
	"hub.title": "鹤城 · 炼金补给站",
	"hub.close": "关闭",
	"hub.board_title": "任务看板",
	"hub.accept": "接取",
	"hub.abandon": "放弃委托",
	"hub.quest_busy": "已有进行中的委托",
	"hub.quest_accepted": "已接取：%s",
	"hub.quest_active": "进行中：%s",
	"hub.quest_target": "进度目标：%s（入坑后实时计数）",
	"hub.quest_progress_hint": "坑内右上角可查看实时进度与详情。",
	"hub.quiet_title": "静室 · 吸收念力",
	"hub.quiet_hint": "当前念力 %d 级。升至下一级需等效碎晶 %d。",
	"hub.quiet_weights": "当前烙印倾向：铁%d%% 铜%d%% 银%d%% 金%d%%",
	"hub.quiet_effect": "升级后烙印倾向：铁%d%% 铜%d%% 银%d%% 金%d%%",
	"hub.quiet_do": "吸收升级",
	"hub.quiet_ok": "念力提升至 %d 级",
	"hub.quiet_max": "念力已达上限",
	"hub.quiet_no": "材料不足",
	"hub.alchemy_title": "炼金台 · 打造强化",
	"hub.craft": "打造",
	"hub.upgrade": "强化",
	"hub.craft_ok": "打造完成：%s",
	"hub.upgrade_ok": "强化成功：%s",
	"hub.craft_cost": "打造需：%s",
	"hub.upgrade_cost": "强化需：%s",
	"hub.cost_lack": "（不足）",
	"hub.no_mats": "材料不足",
	"hub.stash_title": "材料仓库",
	"hub.stash_empty": "仓库空空如也",
	"hub.owned_toast": "已拥有",
	"hub.abandon_toast": "已放弃委托",
	"quest.reward": "奖励：金币 %d；%s",
	"quest.reward_mats_none": "无额外材料",
	"intel.floor_cleared": "记录：曾从第 %d 层成功撤离。",
}


func t(key: String, args: Array = []) -> String:
	var text: String = str(_strings.get(key, key))
	if args.is_empty():
		return text
	return text % args


func has_key(key: String) -> bool:
	return _strings.has(key)
